language: node_js
node_js:
  - '18'
services:
  - mongodb
cache: yarn
branches:
  only:
    - master
env:
  global:
    - PORT=3000
    - MONGODB_URL=
script:
  - yarn lint
  - yarn test
after_success: yarn coverage:coveralls
